name: Deploy site

on:
  workflow_run:
    workflows: ["Build site"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build-site.yml
        workflow_conclusion: success
          
    - name: Copy files
      uses: ulaval/azure-blob-copy-action@v1
      with:
        action: upload
        connection_string: ${{ secrets.AZURE_CREDENTIALS}}
        container_name: $web
        local_directory: production-files
     
    - uses: bacongobbler/azure-blob-storage-upload@main
      with:
          source_dir: production-files
          container_name: $web
          connection_string: ${{ secrets.ConnectionString }}
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'
    
    - name: Azure logout
      run: |
            az logout
