name: Deploy site

on:
  workflow_run:
    workflows: ["Build site"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build-site.yml
        workflow_conclusion: success
    
    - name: Upload to Azure Blob Storage
      uses: bacongobbler/azure-blob-storage-upload@v1.0.0
      with: 
          source_dir: production-files #gatsby build generates this file after build
          container_name: $web
          connection_string: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Upload to Azure blob storage
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
            az storage blob upload-batch --account-name newstoragetestvansh -d '$web' -s ./production-files
    
    - name: Azure logout
      run: |
            az logout
