name: Deploy site

on:
  workflow_run:
    workflows: ["Build site"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: build-site.yml
        workflow_conclusion: success
     
    - uses: bacongobbler/azure-blob-storage-upload@main
      with:
          source_dir: production-files
          container_name: $web
          connection_string: ${{ secrets.AZURE_CREDENTIALS }}
          # WARNING: this will overwrite existing blobs in your blob storage
          overwrite: 'true'
